# Generated by Django 4.1.6 on 2023-03-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_add_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
