# Generated by Django 4.1.6 on 2023-04-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_form',
        ),
    ]
