# Generated by Django 4.1.6 on 2023-04-27 09:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_delete_sign_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('nimg', models.CharField(max_length=266)),
            ],
        ),
    ]
